import Layout from '@admin/views/layout/index.vue'

const roles = ['admin']

export default [
  {
    path: '',
    name: 'homepage',
    component: Layout,
    hidden: true,
    meta: { title: '首页', roles },
  },
  {
    path: '/zhixiang',
    name: 'zhixiang',
    component: Layout,
    meta: { title: '知享', roles, icon: '知享' },
    children: [
      {
        path: 'examination',
        name: 'zhixiang-examination-list',
        component: () => import('./views/zhixiang/ExaminationList.vue'),
        meta: { title: '考试管理', roles, icon: '知享考试' },
      },
      {
        path: 'examination/new',
        name: 'zhixiang-examination-new',
        hidden: true,
        component: () => import('./views/zhixiang/ExaminationEdit.vue'),
        props: { mode: 'new' },
        meta: { title: '新增考试', roles },
      },
      {
        path: 'examination/edit/:id',
        name: 'zhixiang-examination-edit',
        hidden: true,
        component: () => import('./views/zhixiang/ExaminationEdit.vue'),
        props: { mode: 'edit' },
        meta: { title: '修改考试', roles },
      },
      {
        path: 'training',
        name: 'zhixiang-training-list',
        component: () => import('./views/zhixiang/TrainingList.vue'),
        meta: { title: '培训管理', roles, icon: '培训管理' },
      },
      {
        path: 'training/edit/:id',
        name: 'zhixiang-training-edit',
        hidden: true,
        component: () => import('./views/zhixiang/TrainingEdit.vue'),
        props: { mode: 'edit' },
        meta: { title: '资格状态编辑', roles },
      },
      {
        path: 'news',
        name: 'zhixiang-news-list',
        component: () => import('./views/zhixiang/NewsList.vue'),
        meta: { title: '新闻管理', roles, icon: '知享新闻' },
      },
      {
        path: 'news/new',
        name: 'zhixiang-news-new',
        hidden: true,
        component: () => import('./views/zhixiang/NewsEdit.vue'),
        props: { mode: 'new' },
        meta: { title: '新建新闻', roles },
      },
      {
        path: 'news/edit/:id',
        name: 'zhixiang-news-edit',
        hidden: true,
        component: () => import('./views/zhixiang/NewsEdit.vue'),
        props: { mode: 'edit' },
        meta: { title: '编辑新闻', roles },
      },
    ],
  },
  {
    path: '/project',
    name: 'project',
    component: Layout,
    meta: { title: '项目专题', roles, icon: '项目' },
    children: [
      {
        path: 'project',
        name: 'project-project-list',
        component: () => import('./views/project/ProjectList.vue'),
        meta: { title: '项目管理', roles, icon: '项目' },
      },
      {
        path: 'project/new',
        name: 'project-project-new',
        hidden: true,
        component: () => import('./views/project/ProjectEdit.vue'),
        props: { mode: 'new' },
        meta: { title: '新建项目', roles },
      },
      {
        path: 'project/edit/:id',
        name: 'project-project-edit',
        hidden: true,
        component: () => import('./views/project/ProjectEdit.vue'),
        props: { mode: 'edit' },
        meta: { title: '编辑项目', roles },
      },
      {
        path: 'menu/:id',
        name: 'project-menu-edit',
        hidden: true,
        component: () => import('./views/project/NavMenuEdit.vue'),
        props: { mode: 'edit' },
        meta: { title: '菜单管理', roles },
      },
      {
        path: 'page',
        name: 'project-page-list',
        component: () => import('./views/project/PageList.vue'),
        meta: { title: '页面管理', roles, icon: '页面管理' },
      },
      {
        path: 'page/new',
        name: 'project-page-new',
        hidden: true,
        component: () => import('./views/project/PageEdit.vue'),
        props: { mode: 'new' },
        meta: { title: '新建页面', roles },
      },
      {
        path: 'page/edit/:id',
        name: 'project-page-edit',
        hidden: true,
        component: () => import('./views/project/PageEdit.vue'),
        props: { mode: 'edit' },
        meta: { title: '编辑页面', roles },
      },
      {
        path: 'document',
        name: 'project-document-list',
        component: () => import('./views/project/DocumentList.vue'),
        meta: { title: '附件管理', roles, icon: '附件管理' },
      },
      {
        path: 'document/new',
        name: 'project-document-new',
        hidden: true,
        component: () => import('./views/project/DocumentEdit.vue'),
        props: { mode: 'new' },
        meta: { title: '上传附件', roles },
      },
      {
        path: 'document/edit/:id',
        name: 'project-document-edit',
        hidden: true,
        component: () => import('./views/project/DocumentEdit.vue'),
        props: { mode: 'edit' },
        meta: { title: '编辑附件', roles },
      },
    ],
  },
]
