image: registry.natureself.site/ci/base:master

stages:
  - test
  - build
  - deploy

Lint:
  stage: test
  script:
    - npm install
    - npm run eslint
    - npm run stylelint

Build Image:
  stage: build
  script:
    - nsci build-image --project build --repo cardpc-next

Build Production Image:
  stage: build
  only:
    - tags
  script:
    - nsci build-image --project production --repo cardpc-next

Update Testing Env:
  stage: deploy
  when: manual
  only:
    - master
    - /^protected\/.*$/
  script:
    - 'nsci update-kube-service --kubectx bjo --kubens testing --project build --repo cardpc-next deployment/cardpc-next "*"'
