# Generated by Django 2.1.5 on 2019-04-25 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0004_auto_20190425_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('introduction', models.TextField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('thumbnail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.Image')),
            ],
        ),
        migrations.CreateModel(
            name='PresentationLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.TextField()),
                ('summary', models.TextField()),
                ('status', models.IntegerField(choices=[(0, '已删除'), (1, '已发布'), (2, '草稿')], default=2)),
                ('teacher_name', models.TextField()),
                ('teacher_organization', models.TextField()),
                ('teacher_introduction', models.TextField()),
                ('attachments', models.ManyToManyField(related_name='_presentationlesson_attachments_+', to='media.Document')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.Course')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.Presentation')),
                ('teacher_picture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.TextField()),
                ('summary', models.TextField()),
                ('status', models.IntegerField(choices=[(0, '已删除'), (1, '已发布'), (2, '草稿')], default=2)),
                ('teacher_name', models.TextField()),
                ('teacher_organization', models.TextField()),
                ('teacher_introduction', models.TextField()),
                ('attachments', models.ManyToManyField(related_name='_videolesson_attachments_+', to='media.Document')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.Course')),
                ('teacher_picture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Image')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.PolyvVideo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
