# Generated by Django 2.2.1 on 2019-05-08 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='introduction',
            field=models.TextField(verbose_name='课程介绍'),
        ),
        migrations.AlterField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='课程发布者'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.Image', verbose_name='课程缩略图'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.TextField(verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='presentationlesson',
            name='attachments',
            field=models.ManyToManyField(related_name='_presentationlesson_attachments_+', to='media.Document', verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='presentationlesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.Course', verbose_name='所属课程'),
        ),
        migrations.AlterField(
            model_name='presentationlesson',
            name='presentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.Presentation', verbose_name='PPT'),
        ),
        migrations.AlterField(
            model_name='presentationlesson',
            name='status',
            field=models.IntegerField(choices=[(1, '已发布'), (2, '草稿')], default=2, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='presentationlesson',
            name='summary',
            field=models.TextField(verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='presentationlesson',
            name='teacher_introduction',
            field=models.TextField(verbose_name='讲者介绍'),
        ),
        migrations.AlterField(
            model_name='presentationlesson',
            name='teacher_name',
            field=models.TextField(verbose_name='讲者姓名'),
        ),
        migrations.AlterField(
            model_name='presentationlesson',
            name='teacher_organization',
            field=models.TextField(verbose_name='讲者单位'),
        ),
        migrations.AlterField(
            model_name='presentationlesson',
            name='teacher_picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Image', verbose_name='讲者头像'),
        ),
        migrations.AlterField(
            model_name='presentationlesson',
            name='title',
            field=models.TextField(verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='attachments',
            field=models.ManyToManyField(related_name='_videolesson_attachments_+', to='media.Document', verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.Course', verbose_name='所属课程'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='status',
            field=models.IntegerField(choices=[(1, '已发布'), (2, '草稿')], default=2, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='summary',
            field=models.TextField(verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='teacher_introduction',
            field=models.TextField(verbose_name='讲者介绍'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='teacher_name',
            field=models.TextField(verbose_name='讲者姓名'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='teacher_organization',
            field=models.TextField(verbose_name='讲者单位'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='teacher_picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Image', verbose_name='讲者头像'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='title',
            field=models.TextField(verbose_name='标题'),
        ),
    ]
