# Generated by Django 2.2.1 on 2019-05-09 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190508_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationlesson',
            name='teacher_picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='media.Image', verbose_name='讲者头像'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='teacher_picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='media.Image', verbose_name='讲者头像'),
        ),
    ]
