# Generated by Django 2.1.5 on 2019-04-25 05:46

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification', '0002_auto_20190408_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.TextField()),
                ('code', models.TextField()),
                ('generated_at', models.DateTimeField()),
                ('silent_before', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('session_key', models.TextField()),
                ('verify_count', models.IntegerField(default=0)),
                ('used', models.BooleanField(default=False)),
                ('client_meta', jsonfield.fields.JSONField(default=dict)),
                ('usage', models.TextField(choices=[('login', '登录验证码'), ('register', '注册验证码')])),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.Email')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SmsVerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.TextField()),
                ('code', models.TextField()),
                ('generated_at', models.DateTimeField()),
                ('silent_before', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('session_key', models.TextField()),
                ('verify_count', models.IntegerField(default=0)),
                ('used', models.BooleanField(default=False)),
                ('client_meta', jsonfield.fields.JSONField(default=dict)),
                ('usage', models.TextField(choices=[('login', '登录验证码'), ('register', '注册验证码')])),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.AliSms')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
