# Generated by Django 2.1.5 on 2019-03-28 17:23

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AliSms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_numbers', models.TextField()),
                ('signature_name', models.TextField(choices=[('泽创天成', '泽创天成'), ('医维云', '医维云'), ('大鱼测试', '大鱼测试'), ('活动验证', '活动验证'), ('变更验证', '变更验证'), ('登录验证', '登录验证'), ('注册验证', '注册验证'), ('身份验证', '身份验证')])),
                ('template_code', models.TextField(choices=[('SMS_134310520', '您的验证码为 ${code}，此验证码用于您的手机验证。10分钟内有效。'), ('SMS_133972398', '您的验证码：${code}，您正进行身份验证，该验证码5分钟内有效，打死不告诉别人！'), ('SMS_66610220', '验证码${code}，您正在进行${product}身份验证，打死不要告诉别人哦！'), ('SMS_66610219', '尊敬的${customer}，欢迎您使用阿里云通信服务！'), ('SMS_66610218', '验证码${code}，您正在登录${product}，若非本人操作，请勿泄露。'), ('SMS_66610217', '验证码${code}，您正尝试异地登录${product}，若非本人操作，请勿泄露。'), ('SMS_66610216', '验证码${code}，您正在注册成为${product}用户，感谢您的支持！'), ('SMS_66610215', '验证码${code}，您正在参加${product}的${item}活动，请确认系本人申请。'), ('SMS_66610214', '验证码${code}，您正在尝试修改${product}登录密码，请妥善保管账户信息。'), ('SMS_66610213', '验证码${code}，您正在尝试变更${product}重要信息，请妥善保管账户信息。')])),
                ('template_param', jsonfield.fields.JSONField(default=dict)),
                ('access_key_id', models.TextField()),
                ('content', models.TextField()),
                ('ali_bizid', models.TextField()),
                ('ali_code', models.TextField()),
                ('ali_message', models.TextField()),
                ('status', models.TextField(choices=[('pending', '待发送'), ('reject', '拒绝发送'), ('sent', '已发送'), ('success', '发送成功'), ('failed', '发送失败'), ('dryrun', '本地测试')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('from_email', models.TextField()),
                ('recipients', models.TextField()),
                ('content', models.TextField()),
                ('status', models.TextField(choices=[('pending', '待发送'), ('reject', '拒绝发送'), ('sent', '已发送'), ('success', '发送成功'), ('failed', '发送失败'), ('dryrun', '本地测试')])),
                ('local_path', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.TextField()),
            ],
        ),
    ]
