# Generated by Django 2.1.5 on 2019-04-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20190408_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alisms',
            name='signature_name',
            field=models.TextField(choices=[('泽创天成', '泽创天成'), ('医维云', '医维云'), ('医维云科研大数据平台', '医维云科研大数据平台'), ('基层呼吸联盟', '中国基层呼吸防治联盟'), ('大鱼测试', '大鱼测试'), ('活动验证', '活动验证'), ('变更验证', '变更验证'), ('登录验证', '登录验证'), ('注册验证', '注册验证'), ('身份验证', '身份验证')]),
        ),
    ]
