# Generated by Django 2.2.1 on 2019-05-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20190428_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alisms',
            name='signature_name',
            field=models.TextField(choices=[('泽创天成', '泽创天成'), ('医维云', '医维云'), ('医维云科研大数据平台', '医维云科研大数据平台'), ('基层呼吸联盟', '中国基层呼吸防治联盟'), ('中国基层呼吸疾病防治联盟', '中国基层呼吸疾病防治联盟'), ('大鱼测试', '大鱼测试'), ('活动验证', '活动验证'), ('变更验证', '变更验证'), ('登录验证', '登录验证'), ('注册验证', '注册验证'), ('身份验证', '身份验证')]),
        ),
        migrations.AlterField(
            model_name='alisms',
            name='template_code',
            field=models.TextField(choices=[('SMS_134310520', '您的验证码为 ${code}，此验证码用于您的手机验证。10分钟内有效。'), ('SMS_133972398', '您的验证码：${code}，您正进行身份验证，该验证码5分钟内有效，打死不告诉别人！'), ('SMS_66610220', '验证码${code}，您正在进行${product}身份验证，打死不要告诉别人哦！'), ('SMS_66610219', '尊敬的${customer}，欢迎您使用阿里云通信服务！'), ('SMS_66610218', '验证码${code}，您正在登录${product}，若非本人操作，请勿泄露。'), ('SMS_66610217', '验证码${code}，您正尝试异地登录${product}，若非本人操作，请勿泄露。'), ('SMS_66610216', '验证码${code}，您正在注册成为${product}用户，感谢您的支持！'), ('SMS_66610215', '验证码${code}，您正在参加${product}的${item}活动，请确认系本人申请。'), ('SMS_66610214', '验证码${code}，您正在尝试修改${product}登录密码，请妥善保管账户信息。'), ('SMS_66610213', '验证码${code}，您正在尝试变更${product}重要信息，请妥善保管账户信息。'), ('SMS_162524735', '您好，${study}的受试者编号为${case_id}的${event_name}访视${visit_status}，请登录平台查看详情，及时开展访视！'), ('SMS_164800307', '验证码为：${code}，10分钟内有效，若非本人操作请忽略，请勿泄漏验证码。')]),
        ),
    ]
