# Generated by Django 2.2.1 on 2019-05-09 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardpc', '0002_zhixiangexamination_zhixiangnews_zhixiangtrainingdata_squashed_0007_auto_20190508_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZhixiangTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_status', models.IntegerField(choices=[(1, '未参与课程调研'), (2, '已参与课程调研')], default=1, verbose_name='课程调研状态')),
                ('a_start', models.DateTimeField(null=True, verbose_name='课程调研开始时间')),
                ('a_end', models.DateTimeField(null=True, verbose_name='课程调研结束时间')),
                ('b_status', models.IntegerField(choices=[(1, '未学完课程'), (2, '已学完课程')], default=1, verbose_name='培训课程状态')),
                ('c_status', models.IntegerField(choices=[(1, '未参与资格认证'), (2, '已填写问卷星、等待审核'), (3, '审核通过'), (4, '审核未通过')], default=1, verbose_name='资格认证状态')),
                ('c_start', models.DateTimeField(null=True, verbose_name='资格认证开始时间')),
                ('c_end', models.DateTimeField(null=True, verbose_name='资格认证结束时间')),
                ('d_status', models.IntegerField(choices=[(1, '未参与考试'), (2, '已参与考试')], default=1, verbose_name='考试评定状态')),
                ('d_start', models.DateTimeField(null=True, verbose_name='考试评定开始时间')),
                ('d_end', models.DateTimeField(null=True, verbose_name='考试评定结束时间')),
                ('examination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cardpc.ZhixiangExamination', verbose_name='关联考试')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zhixiang_training_data', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.DeleteModel(
            name='ZhixiangTrainingData',
        ),
    ]
