# Generated by Django 2.2.1 on 2019-05-14 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_auto_20190508_2054'),
        ('cardpc', '0003_auto_20190509_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='专题名称')),
                ('theme_color', models.TextField(verbose_name='模板主色彩')),
                ('introduction', models.TextField(verbose_name='专题介绍')),
                ('slug', models.TextField(unique=True, verbose_name='专题地址')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Image', verbose_name='Banner 图片')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('publish_time', models.DateTimeField(verbose_name='发布时间')),
                ('tag', models.TextField(verbose_name='标签')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Document', verbose_name='文件')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cardpc.Project', verbose_name='专题')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachments', models.ManyToManyField(to='cardpc.ProjectDocument', verbose_name='附件')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cardpc.Project', verbose_name='所属专题')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGallery',
            fields=[
                ('projectpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cardpc.ProjectPage')),
            ],
            bases=('cardpc.projectpage',),
        ),
        migrations.CreateModel(
            name='ProjectHomepage',
            fields=[
                ('projectpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cardpc.ProjectPage')),
            ],
            bases=('cardpc.projectpage',),
        ),
        migrations.CreateModel(
            name='ProjectNews',
            fields=[
                ('projectpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cardpc.ProjectPage')),
                ('title', models.TextField(verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('author_name', models.TextField(verbose_name='作者姓名')),
                ('cover_picture', models.TextField(verbose_name='封面图片')),
                ('publish_time', models.TextField(verbose_name='发表时间')),
            ],
            bases=('cardpc.projectpage',),
        ),
        migrations.CreateModel(
            name='ProjectNewsList',
            fields=[
                ('projectpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cardpc.ProjectPage')),
            ],
            bases=('cardpc.projectpage',),
        ),
        migrations.CreateModel(
            name='ProjectRichtextPage',
            fields=[
                ('projectpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cardpc.ProjectPage')),
                ('title', models.TextField(verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
            ],
            bases=('cardpc.projectpage',),
        ),
        migrations.CreateModel(
            name='ProjectNavMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.TextField(choices=[('external', '链接到外部地址'), ('page', '链接到内部页面')], verbose_name='链接类型')),
                ('link_url', models.TextField(blank=True, verbose_name='链接地址')),
                ('text', models.TextField(blank=True, verbose_name='菜单文字')),
                ('link_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardpc.ProjectPage', verbose_name='链接页面')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cardpc.ProjectNavMenu')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cardpc.ProjectNavMenu', verbose_name='导航菜单'),
        ),
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('key', models.TextField(unique=True)),
                ('local_path', models.TextField()),
                ('filename', models.TextField()),
                ('content_type', models.TextField()),
                ('size', models.IntegerField()),
                ('md5sum', models.TextField()),
                ('bucket', models.TextField()),
                ('deleted_at', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='cardpc.ProjectGallery')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
