# Generated by Django 2.2.1 on 2019-05-14 16:29

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cardpc', '0004_auto_20190514_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='theme_color',
        ),
        migrations.AddField(
            model_name='project',
            name='theme_colors',
            field=jsonfield.fields.JSONField(default=dict, verbose_name='主题颜色'),
        ),
    ]
