# Generated by Django 2.2.1 on 2019-05-15 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_auto_20190508_2054'),
        ('cardpc', '0005_auto_20190515_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVideoList',
            fields=[
                ('projectpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cardpc.ProjectPage')),
            ],
            bases=('cardpc.projectpage',),
        ),
        migrations.AddField(
            model_name='project',
            name='theme',
            field=models.TextField(default='default', verbose_name='主题模板名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='introduction',
            field=models.TextField(verbose_name='项目介绍'),
        ),
        migrations.AlterField(
            model_name='project',
            name='menu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='project', to='cardpc.ProjectNavMenu', verbose_name='导航菜单'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.TextField(unique=True, verbose_name='项目地址'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(verbose_name='项目名称'),
        ),
        migrations.CreateModel(
            name='ProjectVideo',
            fields=[
                ('projectpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cardpc.ProjectPage')),
                ('introduction', models.TextField(verbose_name='内容简介')),
                ('teacher_introduction', models.TextField(verbose_name='讲者简介')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.PolyvVideo', verbose_name='关联的保利威视频')),
            ],
            bases=('cardpc.projectpage',),
        ),
    ]
