# Generated by Django 2.2.1 on 2019-05-16 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardpc', '0006_auto_20190515_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDownload',
            fields=[
                ('projectpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cardpc.ProjectPage')),
            ],
            bases=('cardpc.projectpage',),
        ),
    ]
