# Generated by Django 2.2.1 on 2019-05-16 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('cardpc', '0008_auto_20190516_1407'), ('cardpc', '0009_auto_20190517_0011'), ('cardpc', '0010_auto_20190517_0016')]

    dependencies = [
        ('cardpc', '0007_projectdownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='page_title',
            field=models.TextField(default='', verbose_name='网页标题'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cardpc.Project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cardpc.Project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='projectnews',
            name='cover_picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Image', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='projectvideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.PolyvVideo', verbose_name='保利威视频'),
        ),
        migrations.AlterField(
            model_name='projectnews',
            name='publish_time',
            field=models.DateTimeField(verbose_name='发表时间'),
        ),
    ]
