# Generated by Django 2.2.1 on 2019-05-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardpc', '0008_auto_20190516_1407_squashed_0010_auto_20190517_0016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectnavmenu',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='projectnavmenu',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
