# Generated by Django 2.2.1 on 2019-05-20 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardpc', '0009_auto_20190517_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgalleryimage',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectgalleryimage',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='cardpc.ProjectGallery', verbose_name='花絮锦集'),
        ),
    ]
