# Generated by Django 2.2.1 on 2019-05-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardpc', '0010_auto_20190520_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectvideo',
            name='teacher_name',
            field=models.TextField(default='', verbose_name='讲师姓名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectvideo',
            name='teacher_organization',
            field=models.TextField(default='', verbose_name='讲师单位'),
            preserve_default=False,
        ),
    ]
