# Generated by Django 2.2.1 on 2019-05-22 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_auto_20190520_2356'),
        ('cardpc', '0011_auto_20190521_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCarouselItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.TextField(verbose_name='标题')),
                ('link_url', models.TextField(blank=True, verbose_name='链接地址')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.Image', verbose_name='图片')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='projecthomepage',
            name='carousel_items',
            field=models.ManyToManyField(related_name='project_homepage', to='cardpc.ProjectCarouselItem'),
        ),
    ]
