# Generated by Django 2.2.1 on 2019-05-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardpc', '0012_auto_20190522_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='attachments',
            field=models.ManyToManyField(to='media.Document', verbose_name='附件'),
        ),
    ]
