# Generated by Django 2.2.1 on 2019-06-05 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_auto_20190520_2356'),
        ('cardpc', '0013_auto_20190522_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='banner_background',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.Image', verbose_name='Banner 背景图片'),
        ),
        migrations.AlterField(
            model_name='project',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.Image', verbose_name='Banner 图片'),
        ),
    ]
