# Generated by Django 2.2.1 on 2019-06-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardpc', '0014_auto_20190605_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='status',
            field=models.TextField(choices=[('published', '已发布'), ('draft', '草稿')], default='published', verbose_name='状态'),
        ),
    ]
