# Generated by Django 2.2.1 on 2019-06-06 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardpc', '0016_auto_20190605_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='banner_background',
            field=models.ForeignKey(help_text='如果不设置该图片，则 banner 背景使用主题颜色', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.Image', verbose_name='Banner 背景图片'),
        ),
        migrations.AlterField(
            model_name='projectnavmenu',
            name='link_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cardpc.ProjectPage', verbose_name='链接页面'),
        ),
        migrations.AlterField(
            model_name='projectnews',
            name='excerpt',
            field=models.TextField(help_text='在新闻列表页中显示', verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardpc.Project', verbose_name='项目'),
        ),
    ]
