# Generated by Django 2.1.5 on 2019-03-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('local_path', models.TextField()),
                ('filename', models.TextField()),
                ('content_type', models.TextField()),
                ('size', models.IntegerField()),
                ('md5sum', models.TextField()),
                ('bucket', models.TextField()),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('local_path', models.TextField()),
                ('filename', models.TextField()),
                ('content_type', models.TextField()),
                ('size', models.IntegerField()),
                ('md5sum', models.TextField()),
                ('bucket', models.TextField()),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PolyvVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('vid', models.TextField()),
                ('duration', models.TextField()),
            ],
        ),
    ]
