# Generated by Django 2.1.5 on 2019-04-25 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0003_auto_20190422_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolyvLive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('vid', models.TextField()),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('started', models.IntegerField(choices=[(0, '未设置'), (1, '标记为假'), (2, '标记为真')], default=0)),
                ('ended', models.BooleanField(choices=[(0, '未设置'), (1, '标记为假'), (2, '标记为真')], default=0)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('playback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.PolyvVideo')),
                ('thumbnail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Image')),
            ],
        ),
        migrations.CreateModel(
            name='PolyvLiveWatchRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('live', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='media.PolyvLive')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PolyvVideoWatchRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='media.PolyvVideo')),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('thumbnail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Image')),
            ],
        ),
        migrations.CreateModel(
            name='PresentationWatchRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='media.Presentation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('key', models.TextField(unique=True)),
                ('local_path', models.TextField()),
                ('filename', models.TextField()),
                ('content_type', models.TextField()),
                ('size', models.IntegerField()),
                ('md5sum', models.TextField()),
                ('bucket', models.TextField()),
                ('deleted_at', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('presentation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slides', to='media.Presentation')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='presentation',
            name='watched_users',
            field=models.ManyToManyField(related_name='_presentation_watched_users_+', through='media.PresentationWatchRecord', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='polyvlive',
            name='watched_users',
            field=models.ManyToManyField(related_name='_polyvlive_watched_users_+', through='media.PolyvLiveWatchRecord', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='polyvvideo',
            name='watched_users',
            field=models.ManyToManyField(related_name='_polyvvideo_watched_users_+', through='media.PolyvVideoWatchRecord', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='presentationwatchrecord',
            unique_together={('user', 'presentation')},
        ),
        migrations.AlterUniqueTogether(
            name='polyvvideowatchrecord',
            unique_together={('user', 'video')},
        ),
        migrations.AlterUniqueTogether(
            name='polyvlivewatchrecord',
            unique_together={('user', 'live')},
        ),
    ]
