# Generated by Django 2.2.1 on 2019-05-08 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20190425_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='thumbnail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Image', verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='title',
            field=models.TextField(verbose_name='标题'),
        ),
    ]
