# Generated by Django 2.2.1 on 2019-05-16 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_auto_20190508_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polyvvideo',
            name='duration',
            field=models.TextField(verbose_name='视频时长'),
        ),
        migrations.AlterField(
            model_name='polyvvideo',
            name='thumbnail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Image', verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='polyvvideo',
            name='title',
            field=models.TextField(verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='polyvvideo',
            name='vid',
            field=models.TextField(verbose_name='保利威 vid'),
        ),
    ]
