# Generated by Django 2.2.1 on 2019-05-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_auto_20190516_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
