# Generated by Django 2.2.1 on 2019-05-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_auto_20190520_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='polyvvideo',
            name='login_required',
            field=models.BooleanField(default=False, verbose_name='登录才可播放'),
        ),
    ]
