# Generated by Django 2.2.1 on 2019-05-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_polyvvideo_login_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='min_watch_seconds',
            field=models.IntegerField(default=0, verbose_name='最少观看时间'),
        ),
        migrations.AddField(
            model_name='presentationwatchrecord',
            name='watched_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
