# Generated by Django 2.2.1 on 2019-05-20 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_auto_20190520_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationwatchrecord',
            name='watched',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='presentationwatchrecord',
            name='presentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_records', to='media.Presentation'),
        ),
    ]
